#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

runApplication blockMesh

runApplication decomposePar
# runParallel $application

mpirun -np 4 pisoFoam -parallel

runApplication reconstructPar

runApplication foamToVT

#------------------------------------------------------------------------------
